@id={{$dotenv APPID}}
@city=Žilina
@lat=49.2235
@lon=18.7393

### Weather Data
GET https://api.openweathermap.org/data/2.5/weather?q={{city}}&appid={{id}}&units=metric&mode=json HTTP/1.1
Accept: application/json

### Weather Data by location
GET https://api.openweathermap.org/data/2.5/weather?lat={{lat}}&lon={{lon}}&appid={{id}}&units=metric&mode=json HTTP/1.1

### Weather Icon
GET https://openweathermap.org/img/wn/01d@2x.png HTTP/1.1

### Flag Icon flat
GET https://flagsapi.com/DE/flat/64.png HTTP/1.1

### Flag Icon shiny
GET https://flagsapi.com/SK/shiny/64.png HTTP/1.1

### Geocoding location
GET http://api.openweathermap.org/geo/1.0/direct?q={{city}}&limit=1&appid={{id}}

### Forecast Data
GET https://api.openweathermap.org/data/2.5/forecast?q={{city}}&appid={{id}}&units=metric&mode=json HTTP/1.1

### Forecast Data by location
GET https://api.openweathermap.org/data/2.5/forecast?lat={{lat}}&lon={{lon}}&appid={{id}}&units=metric&mode=json HTTP/1.1
